# get user infos by sending token in authorization header on server 1 (port: 3000)
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5OTI4MjYwMX0.QPI4uWArW7u4OHYqt-Vw8Fp4yGH3oEv6GNL5MB6suho

###

# login and get a Token on Auth server (port: 4000)
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}